# Generated by Django 4.1.2 on 2022-10-23 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_ideas_alter_feedback_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='topic',
            new_name='aihe',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='rating',
            new_name='arvosana',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='bad',
            new_name='ideat',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='good',
            new_name='risut',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='ideas',
            new_name='ruusut',
        ),
    ]
