# Generated by Django 4.1.2 on 2022-10-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_rename_topic_feedback_aihe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='nimi',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
