# Generated by Django 4.1.2 on 2022-10-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_feedback_nimi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='nimi',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
