# Generated by Django 4.1.2 on 2022-10-27 14:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_alter_feedback_nimi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='arvosana',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
